blank_issues_enabled: false
contact_links:
  - name: Google Mobile Ads Unity Plugin Support
    url: https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines
    about: Please file non-SDK issues like account- or project-specific issues at the official Google Mobile Ads support channel
